# Generated by Django 5.2.9 on 2025-12-06 04:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=500)),
                ('title_ko', models.TextField()),
                ('title_en', models.TextField(db_column='title_en')),
                ('year', models.IntegerField(null=True)),
                ('plot', models.TextField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=30, null=True)),
                ('difficulty', models.IntegerField(null=True)),
                ('word_avg_level', models.FloatField(blank=True, null=True)),
                ('tree_depth', models.FloatField(blank=True, null=True)),
                ('pron_acc', models.FloatField(blank=True, null=True)),
                ('real_word', models.FloatField(blank=True, null=True)),
                ('clause_ratio', models.FloatField(blank=True, null=True)),
                ('overlap_ratio', models.FloatField(blank=True, null=True)),
                ('phrase_ratio', models.FloatField(blank=True, null=True)),
                ('pp_ratio', models.FloatField(blank=True, null=True)),
                ('rare_word_ratio', models.FloatField(blank=True, null=True)),
                ('slang_ratio', models.FloatField(blank=True, null=True)),
                ('syllable_word', models.FloatField(blank=True, null=True)),
                ('avg_speed', models.FloatField(blank=True, null=True)),
                ('lev_distance', models.FloatField(blank=True, null=True)),
                ('wavve_url', models.URLField(blank=True, null=True)),
                ('watcha_url', models.URLField(blank=True, null=True)),
                ('netflix_url', models.URLField(blank=True, null=True)),
                ('tiving_url', models.URLField(blank=True, null=True)),
                ('coupang_url', models.URLField(blank=True, null=True)),
                ('disney_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='movies.moviedata')),
            ],
            options={
                'ordering': ['-created_time'],
            },
        ),
    ]
