# Generated by Django 5.2.8 on 2025-11-21 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=500)),
                ('title_ko', models.TextField()),
                ('title_en', models.TextField(db_column='title_en')),
                ('year', models.IntegerField()),
                ('plot', models.TextField(null=True)),
                ('runtime', models.IntegerField(null=True)),
                ('genre', models.CharField(max_length=30, null=True)),
                ('difficulty', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'movie_data',
            },
        ),
    ]
