# Generated by Django 5.2.8 on 2025-11-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='pron_acc',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='real_world',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='tree_depth',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='word_avg_level',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
