# Generated by Django 5.2.8 on 2025-12-03 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='avg_speed',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='clause_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='coupang_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='disney_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='lev_distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='netflix_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='overlap_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='phrase_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='pp_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='rare_word_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='slang_ratio',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='syllable_word',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='tiving_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='watcha_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moviedata',
            name='wavve_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='pron_acc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='real_world',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='tree_depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moviedata',
            name='word_avg_level',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='moviedata',
            table=None,
        ),
    ]
