# Generated by Django 5.2.8 on 2025-12-04 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_avg_speed_moviedata_clause_ratio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='moviedata',
            old_name='real_world',
            new_name='real_word',
        ),
    ]
