# Generated by Django 5.2.8 on 2025-11-19 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='english_level',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
