# Generated by Django 5.2.8 on 2025-11-19 12:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_english_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='english_level',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
